### ISSUE TITLE
bfttest independent groups t test vignette example seems to hang

### ISSUE THREAD

**Issue by jlwoodard** [mrzdcmps/changeofevidence#1]
I was running through the vignette provided for changeofevidence, line by line, and when I got to the independent groups example, the example line seems to hang:

> bf.between <- bfttest(value ~ condition, data = df, alternative = "less", prior.loc = 0.1, prior.r = 0.1)
Independent Samples test (N = 200 [100 + 100])
Calculating Sequential Bayes Factors...
First observation with two groups found at N = 101

The example seems to just stop at the last line above. I am using R version 4.4.0 on a MacBook Pro (2021, M1 Pro chip) with MacOS Sonoma 14.4.1. All other lines in the provided vignette run without a problem. I'm not sure why the independent groups example is not working.

**Comment by mrzdcmps** [comment]
Hi, could you specify if there is an Error or Warning message in the console?
Did you run the line
`df <- data.frame(condition = c(rep("exp", 100), rep("con", 100)),
                 value = c(exp, con))`
to create the df dataframe?

**Comment by jlwoodard** [comment]
Hi, yes, I can confirm that I did run the line to create the dataframe. The between t-test did work on my older 2017 Intel-based iMac under R version 4.2.2. I am not sure if it is the R version (4.4.0) or the Apple M1 Pro processor that might be causing a problem. All other lines of code in the vignette execute properly except for the between t-test.

Best regards,

John

**Comment by mrzdcmps** [comment]
Hi John,
I could replicate the issue after updating to R 4.4.0 and just pushed a fix. Update your library by installing again and it should work!
